camera_matrix:
  - - 211.56578063964844
    - 0.0
    - 210.58203125
  - - 0.0
    - 211.56578063964844
    - 119.4901123046875
  - - 0.0
    - 0.0
    - 1.0
coeffs:
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
